import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "./providers";
import { dm_sans, inter } from "./fonts";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
      {/* <NavBar/> */}
        <Providers>
          {children}
          <Toaster />
        </Providers>
        {/* <Footer /> */}
      </body>
    </html>
  );
}

