import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "./Providers";
import { dm_sans, poppins, inter } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
